# Generated by Django 5.2.4 on 2026-01-06 00:15

import apps.core.models
import apps.sales.models
import apps.sales.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gondola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='nome')),
                ('latitude', models.FloatField(help_text='Latitude de referência para a busca de produtos no salão', validators=[apps.sales.validators.PositiveNumberValidator()], verbose_name='latitude')),
                ('longitude', models.FloatField(help_text='Longitude de referência para a busca de produtos no salão', validators=[apps.sales.validators.PositiveNumberValidator()], verbose_name='longitude')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.establishment', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'gôndola',
                'verbose_name_plural': 'gôndolas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GondolaProduct',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.UniqueUUIDGenerator('sales', 'GondolaProduct', 'id'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('gondola_x_position', models.IntegerField(validators=[apps.sales.validators.PositiveNumberValidator()], verbose_name='posição na gondola - eixo X')),
                ('gondola_y_position', models.IntegerField(validators=[apps.sales.validators.PositiveNumberValidator()], verbose_name='posição na gondola - eixo Y')),
                ('gondola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.gondola', verbose_name='gondola')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'gôndola → produto',
                'verbose_name_plural': 'gôndolas → produtos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InformationEmissor',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.UniqueUUIDGenerator('sales', 'InformationEmissor', 'id'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('key', models.CharField(max_length=16, verbose_name='chave de acesso')),
                ('auth', models.CharField(max_length=128, verbose_name='autenticação')),
                ('name', models.CharField(help_text='Identificador do emissor', max_length=255, verbose_name='nome')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.establishment', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'emissor de informação',
                'verbose_name_plural': 'emissores de informação',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CartLocator',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.UniqueUUIDGenerator('sales', 'CartLocator', 'id'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('information_emissor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.informationemissor', verbose_name='emissor de informação')),
            ],
            options={
                'verbose_name': 'Localizador de carrinho',
                'verbose_name_plural': 'Localizadores de carrinho',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalesMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', apps.sales.models.CustomMapField(default=apps.sales.models._load_default_map, verbose_name='Mapa')),
                ('establishment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.establishment', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'mapa',
                'verbose_name_plural': 'mapas',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='gondola',
            constraint=models.UniqueConstraint(fields=('establishment', 'name'), name='unique_establishment_gondola'),
        ),
        migrations.AddConstraint(
            model_name='gondolaproduct',
            constraint=models.UniqueConstraint(fields=('gondola', 'gondola_x_position', 'gondola_y_position'), name='unique_gondola_product_position'),
        ),
    ]
