# Generated by Django 5.2.4 on 2025-12-17 02:33

import apps.sales.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartlocator',
            name='establishment',
        ),
        migrations.AddField(
            model_name='cartlocator',
            name='information_emissor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.informationemissor', verbose_name='emissor de informação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gondola',
            name='latitude',
            field=models.FloatField(help_text='Latitude de referência para a busca de produtos no salão', validators=[apps.sales.validators.PositiveNumberValidator()], verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='gondola',
            name='longitude',
            field=models.FloatField(help_text='Longitude de referência para a busca de produtos no salão', validators=[apps.sales.validators.PositiveNumberValidator()], verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='salesmap',
            name='establishment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.establishment', verbose_name='loja'),
        ),
    ]
