# Generated by Django 5.2.4 on 2025-12-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_cartlocator_establishment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationemissor',
            name='channel',
            field=models.CharField(blank=True, help_text='Identificador do canal de comunicação', max_length=255, null=True, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='informationemissor',
            name='name',
            field=models.CharField(help_text='Identificador do emissor', max_length=255, verbose_name='nome'),
        ),
    ]
