# Generated by Django 5.2.4 on 2025-12-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_informationemissor_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationemissor',
            name='channel',
        ),
        migrations.AddField(
            model_name='informationemissor',
            name='channel_name',
            field=models.CharField(blank=True, help_text='Identificador do canal de comunicação', max_length=255, null=True, verbose_name='Nome do canal'),
        ),
    ]
