# Generated by Django 5.2.4 on 2025-12-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_informationemissor_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationemissor',
            name='channel_name',
        ),
    ]
