# Generated by Django 5.2.4 on 2025-12-22 20:04

import apps.sales.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_remove_informationemissor_channel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesmap",
            name="mesh",
            field=apps.sales.models.CustomMapField(
                default=apps.sales.models._load_default_map, verbose_name="Mesh"
            ),
        ),
    ]
