# Generated by Django 5.2.4 on 2025-07-15 18:51

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
            ],
            options={
                'verbose_name': 'permissão',
                'verbose_name_plural': 'permissões',
                'db_table': 'users_permissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomPermissionGroup',
            fields=[
            ],
            options={
                'verbose_name': 'grupo de permissões',
                'verbose_name_plural': 'grupos de permissões',
                'db_table': 'user_permission_groups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='senha')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='email foi verificado')),
                ('first_name', models.CharField(max_length=128, verbose_name='nome')),
                ('last_name', models.CharField(max_length=254, verbose_name='sobrenome')),
                ('is_staff', models.BooleanField(default=False, verbose_name='é um funcionário')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='é um superusuário')),
                ('is_active', models.BooleanField(default=True, verbose_name='conta está ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data do cadastro')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='data do útimo login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
