# Generated by Django 5.2.4 on 2025-08-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNPJ', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='CNPJ')),
                ('name', models.CharField(max_length=255, verbose_name='nome comercial')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, help_text='Designa que este funcionário tem todas as permissões da loja sem atribuí-las explicitamente', verbose_name='é administrador geral')),
            ],
            options={
                'verbose_name': 'funcionário',
                'verbose_name_plural': 'funcionários',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('is_active', models.BooleanField(default=False, verbose_name='está ativo')),
            ],
            options={
                'verbose_name': 'loja',
                'verbose_name_plural': 'lojas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstablishmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'lojas → grupo',
                'verbose_name_plural': 'lojas → grupos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstablishmentPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('codename', models.CharField(db_index=True, max_length=100, verbose_name='codinome')),
            ],
            options={
                'verbose_name': 'lojas → permissão',
                'verbose_name_plural': 'lojas → permissões',
                'managed': True,
            },
        ),
    ]
