# Generated by Django 5.2.4 on 2025-12-17 00:16

import apps.core.models
import apps.core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNPJ', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='CNPJ')),
                ('name', models.CharField(max_length=255, verbose_name='nome comercial')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True, verbose_name='palavra-chave')),
            ],
            options={
                'verbose_name': 'produto → palavra-chave',
                'verbose_name_plural': 'produtos → palavras-chave',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=256, verbose_name='Endereço')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='está ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'loja',
                'verbose_name_plural': 'lojas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstablishmentPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('codename', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='codinome')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.establishment', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'lojas → permissão',
                'verbose_name_plural': 'lojas → permissões',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstablishmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.establishment', verbose_name='loja')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas para o grupo.', to='business.establishmentpermission', verbose_name='permissões')),
            ],
            options={
                'verbose_name': 'lojas → grupo',
                'verbose_name_plural': 'lojas → grupos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstablishmentEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, help_text='Designa que este funcionário tem todas as permissões da loja sem atribuí-las explicitamente', verbose_name='é administrador geral')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.establishment', verbose_name='loja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('groups', models.ManyToManyField(blank=True, db_index=True, help_text='Grupos que o funcionário faz parte.', to='business.establishmentgroup', verbose_name='grupos da loja')),
                ('permissions', models.ManyToManyField(blank=True, db_index=True, help_text='Permissões específicas para o funcionário.', to='business.establishmentpermission', verbose_name='permissões da loja')),
            ],
            options={
                'verbose_name': 'funcionário',
                'verbose_name_plural': 'funcionários',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', apps.core.models.CustomImageField(blank=True, height=256, null=True, subdir='uploads/images/products/photo/', upload_to=apps.core.utils.PathAndRename('uploads/images/products/photo/'), verbose_name='Foto', width=256)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='nome')),
                ('barcode', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='código de barra')),
                ('is_active', models.BooleanField(default=False, verbose_name='está ativo')),
                ('keywords', models.ManyToManyField(blank=True, to='business.productkeyword', verbose_name='palavras-chave')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='establishmentpermission',
            constraint=models.UniqueConstraint(fields=('establishment', 'codename'), name='unique_establishment_permission'),
        ),
        migrations.AddConstraint(
            model_name='establishmentgroup',
            constraint=models.UniqueConstraint(fields=('establishment', 'name'), name='unique_establishment_group'),
        ),
        migrations.AddConstraint(
            model_name='establishmentemployee',
            constraint=models.UniqueConstraint(fields=('establishment', 'user'), name='unique_employee'),
        ),
    ]
