# Generated by Django 5.2.4 on 2025-11-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='address',
            field=models.TextField(default='Lorem ipsum', max_length=256, verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
