# Generated by Django 5.2.4 on 2025-08-12 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='store',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.company', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='employee',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.store', verbose_name='loja'),
        ),
        migrations.AddField(
            model_name='storegroup',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.store', verbose_name='loja'),
        ),
        migrations.AddField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos que o funcionário faz parte.', to='business.storegroup', verbose_name='grupos da loja'),
        ),
        migrations.AddField(
            model_name='storepermission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='storepermission',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.store', verbose_name='loja'),
        ),
        migrations.AddField(
            model_name='storegroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas para o grupo.', to='business.storepermission', verbose_name='permissões'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas para o funcionário.', to='business.storepermission', verbose_name='permissões da loja'),
        ),
        migrations.AddConstraint(
            model_name='storepermission',
            constraint=models.UniqueConstraint(fields=('store', 'codename'), name='unique_store_permission'),
        ),
        migrations.AddConstraint(
            model_name='storegroup',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique_store_group'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('store', 'user'), name='unique_employee'),
        ),
    ]
