# Generated by Django 5.2.4 on 2025-08-21 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.company', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='employee',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.establishment', verbose_name='loja'),
        ),
        migrations.AddField(
            model_name='establishmentgroup',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.establishment', verbose_name='loja'),
        ),
        migrations.AddField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Grupos que o funcionário faz parte.', to='business.establishmentgroup', verbose_name='grupos da loja'),
        ),
        migrations.AddField(
            model_name='establishmentpermission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='establishmentpermission',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.establishment', verbose_name='loja'),
        ),
        migrations.AddField(
            model_name='establishmentgroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas para o grupo.', to='business.establishmentpermission', verbose_name='permissões'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permissions',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Permissões específicas para o funcionário.', to='business.establishmentpermission', verbose_name='permissões da loja'),
        ),
        migrations.AddConstraint(
            model_name='establishmentpermission',
            constraint=models.UniqueConstraint(fields=('establishment', 'codename'), name='unique_establishment_permission'),
        ),
        migrations.AddConstraint(
            model_name='establishmentgroup',
            constraint=models.UniqueConstraint(fields=('establishment', 'name'), name='unique_establishment_group'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('establishment', 'user'), name='unique_employee'),
        ),
    ]
