# Generated by Django 5.2.4 on 2025-08-25 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='nome')),
                ('codebar', models.CharField(max_length=80, unique=True, verbose_name='código de barra')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True, verbose_name='palavra-chave')),
            ],
            options={
                'verbose_name': 'palavra-chave',
                'verbose_name_plural': 'palavras-chave',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='establishment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='está ativo'),
        ),
        migrations.CreateModel(
            name='EstablishmentProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', models.JSONField()),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.establishment', verbose_name='loja')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'produto da loja',
                'verbose_name_plural': 'produtos da loja',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='business.productkeyword', verbose_name='palavras-chave'),
        ),
    ]
